# Generated by Django 5.2.5 on 2025-08-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="desctiption",
            new_name="description",
        ),
    ]
