# Generated by Django 5.2.5 on 2025-08-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="Cart",
            new_name="cart",
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="quality",
            new_name="quantity",
        ),
    ]
