# Generated by Django 5.2.5 on 2025-08-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_rename_cart_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="card_id",
            new_name="cart_id",
        ),
    ]
