# Generated by Django 5.2.5 on 2025-08-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_rename_card_id_cart_cart_id"),
        ("store", "0005_rename_variation_category_variation_variation_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
